### ISSUE TITLE
Python 3.10 | MacOS BigSur | Using finder_sidebar_editor

### ISSUE THREAD

**Issue by MohammadEImmam** [robperc/FinderSidebarEditor#9]
```
from finder_sidebar_editor import FinderSidebar

sidebar = FinderSidebar()

sidebar.remove("iCloud")
```
```
Traceback (most recent call last):
  File "/Users/*****/PycharmProjects/findersidebar/main.py", line 5, in <module>
    sidebar.remove("iCloud")
  File "/Users/*****/PycharmProjects/findersidebar/venv/lib/python3.10/site-packages/finder_sidebar_editor/FinderSidebarEditor.py", line 174, in remove
    if to_rm.upper() == name.upper():
AttributeError: 'NoneType' object has no attribute 'upper'

Process finished with exit code 1
```

**Comment by Ajordat** [comment]
Apologies for the late comment. This looks to me like either no display name was found or a None value was given to the `remove` method. Most likely the later, so I would try debugging that first.

Whenever I can I will add some checks to ensure that the proper parameters are given.

**Comment by robperc** [comment]
It looks like you're trying to remove iCloud, which is a 'FavoriteVolume', and not a 'FavoriteItem'. As it stands today only 'FavoriteItem' items are supported. See https://github.com/robperc/FinderSidebarEditor/issues/10 for more details.
